apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: influxdb:1.7.10-alpine
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8086